volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: empirer777/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
    restart: always

  frontend:
    image: empirer777/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  gateway:
    image: empirer777/foodgram_gateway
    env_file: .env
    depends_on:
      - frontend
    volumes:
      - static:/staticfiles/
      - media:/app/media
      # - redoc:/usr/share/nginx/html/api/docs/
      # - front_build:/usr/share/nginx/html/frontend/
    ports:
      - 7000:80
    restart: always